version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: talmud_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - talmud_net

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: talmud_tunnel
    command: tunnel --url http://n8n:5678
    restart: unless-stopped
    networks:
      - talmud_net
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: talmud_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=https://acting-asn-bugs-incorporate.trycloudflare.com
      - GENERIC_TIMEZONE=Asia/Jerusalem
      - N8N_SECURE_COOKIE=false
    # command: "start --tunnel"

    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - talmud_net
    depends_on:
      - qdrant

volumes:
  n8n_data:
  qdrant_data:


networks:
  talmud_net:
    driver: bridge
