"""
Base connector interface for all database types.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


@dataclass
class TableSchema:
    """Represents a single table/collection schema."""
    name: str
    db_type: str  # "sql" | "mongodb" | "redis" etc.
    columns: list[dict[str, Any]] = field(default_factory=list)
    sample_rows: list[dict[str, Any]] = field(default_factory=list)
    row_count: int = 0
    relationships: list[dict[str, str]] = field(default_factory=list)


@dataclass
class DatabaseProfile:
    """Full profile of a database, generated by auto-analysis."""
    db_type: str
    db_name: str
    tables: list[TableSchema] = field(default_factory=list)
    total_rows: int = 0
    raw_ddl: str = ""

    def summary(self) -> str:
        lines = [
            f"Database: {self.db_name} ({self.db_type})",
            f"Tables/Collections: {len(self.tables)}",
            f"Total rows: {self.total_rows}",
            "",
        ]
        for t in self.tables:
            cols = ", ".join(c["name"] for c in t.columns[:8])
            suffix = "..." if len(t.columns) > 8 else ""
            lines.append(f"  - {t.name} ({t.row_count} rows): [{cols}{suffix}]")
        return "\n".join(lines)


class BaseConnector(ABC):
    """Abstract connector — each DB type implements this."""

    @abstractmethod
    def connect(self) -> None:
        ...

    @abstractmethod
    def analyze_schema(self) -> DatabaseProfile:
        ...

    @abstractmethod
    def extract_documents(self, table_name: str, limit: int = 1000) -> list[dict]:
        ...

    @abstractmethod
    def close(self) -> None:
        ...
